name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Push changes
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.SERVER_SSH_KEY }}
        passphrase: ${{ secrets.SERVER_SSH_KEY_PASSPHRASE }}
        source: "."
        target: "/root/university-system"
        rm: true
      
    - name: SSH to server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.SERVER_SSH_KEY }}
        passphrase: ${{ secrets.SERVER_SSH_KEY_PASSPHRASE }}
        script: |
          docker stop university-system-webdev-1 university-system-worker-1
          cp /root/.env /root/university-system/common/config/
          cd /root/university-system
          docker compose -f docker-compose-prod.yml up -d
          docker exec university-system-webdev-1 php init --env=Production
          docker exec university-system-webdev-1 composer i
          docker exec university-system-webdev-1 php yii migrate --interactive=0
          docker exec university-system-webdev-1 php yii cache/flush-all --interactive=0
